### ISSUE TITLE
Vimux doesn't work on latest version of tmux on ubuntu

### ISSUE THREAD

**Issue by altosaar** [preservim/vimux#145] opened 2016-11-24 16:27 UTC
Vimux doesn't seem to work with the latest version of `tmux-next`: https://launchpad.net/~pi-rho/+archive/ubuntu/dev

(on the same ubuntu machine, the old version of tmux, 1.9, works with Vimux just fine)

The commands VimuxRun* don't run in a tmux pane. Happy to provide further details!

**Comment by bubuzzz** [comment] 2016-12-13 03:18
I can confirm this does not work on the latestest tmux 

```
bubuzzzs-MBP:.vim bubuzzz$ tmux -V
tmux 2.3
```

when i type in vim 

`:call VimuxRunComman("ls")`

nothing happens

**Comment by benzittlau** [comment] 2017-01-20 22:06
I'm seeing the same thing:

```
✗ tmux -V
tmux 2.2
```

when I run 

`:call VimuxRunComman("ls")`

I also see nothing run in the pane when it's open, or a pane opened if it's not.

**Comment by dkrieger** [comment] 2017-01-20 22:34
I'm running tmux 2.3 and I don't have this problem. I'm using my fork, on which I implemented a new option for choosing the runner pane that uses the last tmux pane you were in. It's possible that my fork works and the main branch doesn't, I wouldn't know

**Comment by benzittlau** [comment] 2017-01-20 22:49
@dkrieger could you link to your fork?

**Comment by dkrieger** [comment] 2017-01-20 22:54
https://github.com/dkrieger/vimux

**Comment by prescottbreeden** [comment] 2019-10-31 04:17
Running tmux 2.6 and on ubuntu 18.04 I have the same error even with the settings @dkrieger listed - any commands I try just return me to vim without opening a runner - very cool plugin though, will be excited if there is a linux fix

**Comment by alerque** [comment] 2021-02-14 08:30
I don't think the changes in the fork have anything to do with this. In any event see #143 for the PR seeking to merge those features.

If anything this could be a duplicate of #167, but there isn't really enough information here to work with. I've been using Vimux across every version of Tmux from the 1.x erra to the current 3.x releases without this problem, so it isn't directly Tmux version related. I suspect some other confounding circumstances on the host machine, but there isn't enough information here to solve it.

If this is still and issue for you or anyone please comment here and we'll try to track it down. Otherwise with it known to be working for most people there really isn't anything we know to fix

**Closed by alerque** 2021-02-14 08:30 UTC
